swagger: '2.0'
info:
  title: DNS API
  description: Handle the DNS settings
  version: "0.11.0"

schemes:
  - http
  - https
produces:
  - application/json
paths:
  /network/dns:
    get:
      summary: Information of Current DNS settings
      description: |
        List all current DNS and DNS source.
      responses:
        200:
          description: DNS
          schema:
            $ref: '#/definitions/DNS_GET'
          examples:
            {
              "application/json": {
                $ref: '#/externalDocs/x-mocks/DNS_GET'
              }
            }
    put:
      summary: Update DNS settings
      description: Update DNS settings by interface or using fixed DNS.
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/DNS_PUT'
          examples:
            {
              "application/json": {
                $ref: '#/externalDocs/x-mocks/DNS_PUT'
              }
            }
definitions:
  DNS_GET:
    title: DNS_GET
    required:
    - enableFixed
    properties:
      source:
        type: string
        description: |
          the current dns corresponging source (maybe network interface or
          `fixed` DNS)
      dns:
        type: array
        items:
          type: string
          pattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$
        description: Current DNS setting.
      enableFixed:
        type: boolean
        description: |
          Using fixed DNS (true) or by interface (false), false if not given.
      fixedDNS:
        type: array
        items:
          type: string
          pattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$
        description: |
          DNS settings if enableFixed is `true`.
    example:
          $ref: '#/externalDocs/x-mocks/DNS_GET'
  DNS_PUT:
    title: DNS_PUT
    required:
      - enableFixed
    properties:
      enableFixed:
        type: boolean
        description: |
          Using fixed DNS (true) or by interface (false), false if not given.
      fixedDNS:
        type: array
        items:
          type: string
          pattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$
        description: |
          DNS settings if enableFixed is `true`.
    example:
          $ref: '#/externalDocs/x-mocks/DNS_PUT'

externalDocs:
  url: '#'
  x-mocks:
    DNS_GET:
      {
        "enableFixed": false,
        "fixedDNS": [],
        "source": "eth0",
        "dns": [
          "8.8.8.8",
          "8.8.4.4",
        ]
      }
    DNS_PUT:
      {
        "enableFixed": false,
        "fixedDNS": [],
      }
